### ISSUE TITLE
Cannot install vimb

### ISSUE THREAD

**Issue by VehementHam** [jjakob/gentoo-overlay#4]
I get this error when runnig `emerge --sync`:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/emerge", line 57, in main
    retval = emerge_main()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_emerge/main.py", line 1267, in emerge_main
    emerge_config = load_emerge_config(action=myaction, args=myfiles, opts=myopts)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/proxy/objectproxy.py", line 31, in __call__
    return result(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_emerge/actions.py", line 2909, in load_emerge_config
    setconfig = load_default_config(settings, root_trees)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/_sets/__init__.py", line 382, in load_default_config
    return SetConfig(_getfiles(), settings, trees)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/_sets/__init__.py", line 63, in __init__
    read_configs(self._parser, paths)
  File "/usr/lib/python3.11/site-packages/portage/util/configparser.py", line 49, in read_configs
    for p in paths:
  File "/usr/lib/python3.11/site-packages/portage/_sets/__init__.py", line 357, in _getfiles
    for repo in trees["porttree"].dbapi.repositories
                ~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 1679, in __getitem__
    result = lazy_item.func(*pargs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/dbapi/porttree.py", line 1539, in __init__
    self.dbapi = portdbapi(mysettings=settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/dbapi/porttree.py", line 242, in __init__
    self.doebuild_settings = config(clone=self.settings)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/package/ebuild/config.py", line 357, in __init__
    self._mask_manager_obj = clone._mask_manager
                             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/package/ebuild/config.py", line 1354, in _mask_manager
    self._mask_manager_obj = MaskManager(
                             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/package/ebuild/_config/MaskManager.py", line 138, in __init__
    append_repo(stack_lists(lines), repo.name, remember_source_file=True)
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 306, in append_repo
    return [
           ^
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 307, in <listcomp>
    (atom.repo is not None and atom or atom.with_repo(repo_name), source)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/dep/__init__.py", line 1767, in with_repo
    return Atom(atom, allow_repo=True, allow_wildcard=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/dep/__init__.py", line 1527, in __init__
    raise InvalidAtom(self)
portage.exception.InvalidAtom: x11-libs/snorenotify::www-client/vimb
```

**Comment by jjakob** [comment]
That looks like a syntax error in one of your configuration files that
contains the line "x11-libs/snorenotify::www-client/vimb"

I'm guessing, if it's in accept.keywords, the syntax is
"category/package::repository" so "www-client/vimb" is clearly not
supposed to be where a repo name is supposed to be. If it's not in
accept.* the syntax might be even more different/wrong.
